// @flow

const CONFIGURE_TENDENCY = 'CONFIGURE_TENDENCY'
const RESTORE_SESSION_FROM_QUERY = 'RESTORE_SESSION_FROM_QUERY'
const NEXT_QUESTION = 'NEXT_QUESTION'
const ANSWER = 'ANSWER'

export {
  CONFIGURE_TENDENCY,
  RESTORE_SESSION_FROM_QUERY,
  NEXT_QUESTION,
  ANSWER,
}
