// @flow

const RESET_ALL = 'RESET_ALL'
const MORE_FEEDBACK = 'MORE_FEEDBACK'
const EXIT_FEEDBACK = 'EXIT_FEEDBACK'
const CONFIGURE_TENDENCY = 'CONFIGURE_TENDENCY'
const RESTORE_SESSION_FROM_QUERY = 'RESTORE_SESSION_FROM_QUERY'
const NEXT_QUESTION = 'NEXT_QUESTION'
const ANSWER = 'ANSWER'

export {
  RESET_ALL,
  MORE_FEEDBACK,
  EXIT_FEEDBACK,
  CONFIGURE_TENDENCY,
  RESTORE_SESSION_FROM_QUERY,
  NEXT_QUESTION,
  ANSWER,
}
